### ISSUE TITLE
Bug "Create Fireworks App" tutorial 

### ISSUE THREAD

**Issue by andregri** [krateoplatformops/krateo-docs#9]
I found some issues in the deployment of the [fireworks app tutorial](https://docs.krateo.io/tutorials/create-fireworks-app/):
- the Documentation and the Pipelines tabs return 404
- the host in the ingress rule is fixed to `fireworks.krateo.site` even if it was changed during deployment configuration

**Comment by braghettos** [comment]
Hi @andregri, 

> the Documentation and the Pipelines tabs return 404 

Could you please check if the repository has been created?

> the host in the ingress rule is fixed to fireworks.krateo.site even if it was changed during deployment configuration

That's really strange, could you please post the values.yaml file committed via Krateo?

**Comment by andregri** [comment]
I made two tests:
- Test 1: `organizationName: krateoplatformops`. All resources are created correctly apart from the Docoumentation and Pipeline tabs. The application host is `host: fireworks-app.example.com` because I guess it is taken from the https://github.com/krateoplatformops/guest-fire-firefire repository, right?

`values.yaml` of test 1 taken from Values tab:
```yaml
apiVersion: deployment.krateo.io/v1alpha1
kind: FireworksApp
metadata:
  labels:
    crossplane.io/composite: firefire-fireworksapp
  name: firefire-fireworksapp
  uid: 1319382e-e266-4e50-8b0e-54d00314f245
spec:
  compositionRef:
    name: fireworksapp.deployment.krateo.io
  compositionRevisionRef:
    name: fireworksapp.deployment.krateo.io-9353ac7
  compositionUpdatePolicy: Automatic
  description: Fireworks App Deployment
  flat:
    destinationEndpoint: github.com
    host: fireworks-app.example.com
    name: firefire
    organizationName: krateoplatformops
    replicas: 3
  icon: fa-solid fa-fire
  links:
    - icon: fa-brands fa-git
      title: krateoplatformops/guest-fire-firefire
      url: https://github.com/krateoplatformops/guest-fire-firefire
  owner: mauro
  plugins:
    - endpointName: argocd
      icon: fa-solid fa-diagram-project
      name: resources
      type: argocd
      value: firefire-fireworksapp
    - endpointName: github
      icon: fa-solid fa-book
      name: documentation
      type: doc
      values:
        - '[krateoplatformops][guest-fire-firefire]README.md'
    - icon: fa-brands fa-docker
      name: kubernetes
      type: kubernetes
      value: deploymentId
    - endpointName: github
      icon: fa-solid fa-person-running
      name: pipelines
      type: pipeline
      values:
        - >-
          [krateoplatformops][guest-fire-firefire]Build Docker image for every
          commit
  resourceRefs:
    - apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: ProviderConfig
      name: firefire-fireworksapp-provider-k8s-pc-in
    - apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      name: firefire-fireworksapp-argocd-app-object
    - apiVersion: git.krateo.io/v1alpha1
      kind: ProviderConfig
      name: firefire-fireworksapp-provider-git-pc
    - apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      name: firefire-fireworksapp-fireworksapp-values
    - apiVersion: git.krateo.io/v1alpha1
      kind: Repo
      name: firefire-fireworksapp-8qjg4
    - apiVersion: github.krateo.io/v1alpha1
      kind: ProviderConfig
      name: firefire-fireworksapp-provider-github-pc
    - apiVersion: github.krateo.io/v1alpha1
      kind: Repo
  tags:
    - fireworks
    - template
    - krateo
    - katy perry
  templateName: krateo-fireworks
  title: firefire
  values:
    endpointName: github.com
    fromRepo:
      organizationName: krateoplatformops
      repositoryName: krateo-template-fireworksapp
      schema: https
    host: fireworks-app.example.com
    namespace: krateo-system
    organizationName: krateoplatformops
    replicas: 3
    repositoryName: guest-fire-firefire
    toRepo:
      organizationName: krateoplatformops
      repositoryName: guest-fire-firefire
      schema: https
```

- Test 2: `organizationName: andregri`. The repository is not created and Events tab shows:
```
WARNING repository not found
```

The `values.yaml` from Values tab is:
```yaml
apiVersion: deployment.krateo.io/v1alpha1
kind: FireworksApp
metadata:
  labels:
    crossplane.io/composite: firefire2-fireworksapp
  name: firefire2-fireworksapp
  uid: 7cbade9c-5ad2-4244-b9a9-0c0b30aa88bf
spec:
  compositionRef:
    name: fireworksapp.deployment.krateo.io
  compositionRevisionRef:
    name: fireworksapp.deployment.krateo.io-9353ac7
  compositionUpdatePolicy: Automatic
  description: Fireworks App Deployment
  flat:
    destinationEndpoint: github.com
    host: fireworks-app.example.com
    name: firefire2
    organizationName: andregri
    replicas: 3
  icon: fa-solid fa-fire
  links:
    - icon: fa-brands fa-git
      title: andregri/guest-fire-firefire2
      url: https://github.com/andregri/guest-fire-firefire2
  owner: mauro
  plugins:
    - endpointName: argocd
      icon: fa-solid fa-diagram-project
      name: resources
      type: argocd
      value: firefire2-fireworksapp
    - endpointName: github
      icon: fa-solid fa-book
      name: documentation
      type: doc
      values:
        - '[andregri][guest-fire-firefire2]README.md'
    - icon: fa-brands fa-docker
      name: kubernetes
      type: kubernetes
      value: deploymentId
    - endpointName: github
      icon: fa-solid fa-person-running
      name: pipelines
      type: pipeline
      values:
        - '[andregri][guest-fire-firefire2]Build Docker image for every commit'
  resourceRefs:
    - apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: ProviderConfig
      name: firefire2-fireworksapp-provider-k8s-pc-in
    - apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      name: firefire2-fireworksapp-argocd-app-object
    - apiVersion: git.krateo.io/v1alpha1
      kind: ProviderConfig
      name: firefire2-fireworksapp-provider-git-pc
    - apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      name: firefire2-fireworksapp-fireworksapp-values
    - apiVersion: git.krateo.io/v1alpha1
      kind: Repo
      name: firefire2-fireworksapp-p4nnm
    - apiVersion: github.krateo.io/v1alpha1
      kind: ProviderConfig
      name: firefire2-fireworksapp-provider-github-pc
    - apiVersion: github.krateo.io/v1alpha1
      kind: Repo
  tags:
    - fireworks
    - template
    - krateo
    - katy perry
  templateName: krateo-fireworks
  title: firefire2
  values:
    endpointName: github.com
    fromRepo:
      organizationName: krateoplatformops
      repositoryName: krateo-template-fireworksapp
      schema: https
    host: fireworks-app.example.com
    namespace: krateo-system
    organizationName: andregri
    replicas: 3
    repositoryName: guest-fire-firefire2
    toRepo:
      organizationName: andregri
      repositoryName: guest-fire-firefire2
      schema: https
```

**Comment by braghettos** [comment]
To create a repository on GitHub, you must provide an endpoint (https://docs.krateo.io/tutorials/add-endpoint/) that can access an organization (in your case, `andregri`).

The composition uses several providers, like [provider-github](https://github.com/krateoplatformops/provider-github) and  [provider-git](https://github.com/krateoplatformops/provider-git) which should be installed by default with the Krateo CLI. 

In your installation of Krateo PlatformOps, could you check if the previous providers are installed via `kubectl get pkg` or navigating the 'Packages' section in the UI? 

If everything is correctly installed, could you inspect the Custom Resources created by Krateo with `kubectl get managed`?

**Comment by andregri** [comment]
> The composition uses several providers, like [provider-github](https://github.com/krateoplatformops/provider-github) and [provider-git](https://github.com/krateoplatformops/provider-git) which should be installed by default with the Krateo CLI.

As shown below I don't have the **provider-github** installed by default:

```console
$ kubectl get pkg
NAME                                                               INSTALLED   HEALTHY   PACKAGE                                                         AGE
configuration.pkg.crossplane.io/krateo-module-core-configuration   True        True      ghcr.io/krateoplatformops/krateo-module-core:latest             79m
configuration.pkg.crossplane.io/krateo-template-fireworksapp       True        True      ghcr.io/krateoplatformops/krateo-template-fireworksapp:latest   65m

NAME                                                  INSTALLED   HEALTHY   PACKAGE                                                         AGE
provider.pkg.crossplane.io/provider-argocd-endpoint   True        True      ghcr.io/krateoplatformops/provider-argocd-endpoint:v1.0.0       79m
provider.pkg.crossplane.io/provider-git               True        True      ghcr.io/krateoplatformops/provider-git:v1.2.5                   79m
provider.pkg.crossplane.io/provider-helm              True        True      xpkg.upbound.io/crossplane-contrib/provider-helm:v0.13.0        79m
provider.pkg.crossplane.io/provider-kubernetes        True        True      xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.6.0   79m
```

**Comment by braghettos** [comment]
Ok so you can install the provider-github via UI (section 'Packages', + button on the top right, choose 'PROVIDER GITHUB' and install it) or via kubectl (i.e. https://github.com/krateoplatformops/provider-github/blob/main/examples/provider.yaml changing the appropriated values)

**Comment by andregri** [comment]
Yes I installed successfully the github provider from kubectl. I couldn't install it from the UI.

However, after creating the template and the deployment, Github complained about missing permissions in the token:
```
command error on refs/heads/main: refusing to allow a Personal Access Token to create or update workflow `.github/workflows/docker-build.yaml` without `workflow` scope
```

I added the **workflow** scope to the token (I think we should update the [github token doc page](https://docs.krateo.io/tutorials/add-endpoint/#github-token) ) and krateo created the repository 🚀

But the Github workflow of the [created repository](https://github.com/andregri/guest-fire-firefire) is failing due to an error during pushing even if the github token has **write:packages** permission:
```
ERROR: failed to solve: failed to push ghcr.io/andregri/guest-fire-firefire:latest: unexpected status: 403 Forbidden
Error: buildx failed with: ERROR: failed to solve: failed to push ghcr.io/andregri/guest-fire-firefire:latest: unexpected status: 403 Forbidden
```

**Comment by andregri** [comment]
I solved the Github Action error by adding write permissions to the push job (fix commit [here](https://github.com/andregri/guest-fire-firefire/commit/c9c36be2de6be50fd8f27a8bad10ab2199d5825f)):
```yaml
name: Build Docker image for every commit

on:
  push:
    branches: "**"

env:
  IMAGE_TAG: "latest"

jobs:
  push:
    name: Create docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
# omitted
```

The fireworks app is up now 🎆 

Documentation and Pipelines tabs still in error...

**Comment by braghettos** [comment]
@andregri do you see a GitHub Workflow started in the new GitHub repository?

**Comment by andregri** [comment]
I see 3 workflows: the first 2 workflows launched by Krateo, the third workflow launched after my commit:

<img width="1422" alt="Screenshot 2023-03-28 at 14 17 50" src="https://user-images.githubusercontent.com/22377285/228233771-d84e366e-33bf-4faa-bf70-9d1c0cac95ef.png">

**Comment by braghettos** [comment]
Pipelines tabs is configured within the values.yaml from Values tab:

```
  plugins:
    - endpointName: github
      icon: fa-solid fa-person-running
      name: pipelines
      type: pipeline
      values:
        - '[andregri][guest-fire-firefire2]Build Docker image for every commit'
```
Your repo is guest-fire-firefire, not guest-fire-firefire2. Could you post values for guest-fire-firefire2? Could you post logs of the pipeline-service pod?
